# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "APP CLIENT ID"
name = "APP NAME"
handle = "app-handle"
application_url = "https://TUNNEL-URL"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "DEV STORE URL"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders,read_inventory,read_locations,read_orders,read_products,write_draft_orders,write_locations,write_products"

[auth]
redirect_urls = [
  "https://TUNNEL-URL/",
  "https://TUNNEL-URL/auth",
  "https://TUNNEL-URL/auth/callback"
]

[webhooks]
api_version = "2024-04"

[webhooks.privacy_compliance]
customer_deletion_url = "https://TUNNEL-URL/webhooks/customer/delete"
customer_data_request_url = "https://TUNNEL-URL/webhooks/customer/request"
shop_deletion_url = "https://TUNNEL-URL/webhooks/shop/delete"

[pos]
embedded = false

[app_preferences]
url = "https://TUNNEL-URL/preferences"
