// Generated by Wrangler on Mon Apr 01 2024 23:25:42 GMT-0700 (Mountain Standard Time)
// by running `wrangler types`

interface Env {
	APP_URL: "https://shopifyappdev1.innovonics.com";
	SHOPIFY_APP_SCOPES: "read_products,write_products,read_script_tags,write_script_tags";
	SHOPIFY_APP_KEY: string;
	SHOPIFY_APP_SCOPE: string;
	SHOPIFY_APP_SECRET: string;
	DB: D1Database;
}
